# Generated by Django 2.1.5 on 2019-02-03 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0001_initial'),
        ('billing', '0002_auto_20190203_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommisionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('agen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instansale_trx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.InstanSale')),
                ('prev_com', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.CommisionRecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
