# Generated by Django 2.1.5 on 2019-02-07 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_profitrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='delete_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commisionrecord',
            name='delete_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commisionrecord',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='delete_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profitrecord',
            name='delete_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profitrecord',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='instansale_trx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_instan_trx', to='transaction.InstanSale'),
        ),
        migrations.AlterField(
            model_name='commisionrecord',
            name='instansale_trx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commision_instan_trx', to='transaction.InstanSale'),
        ),
        migrations.AlterField(
            model_name='loanrecord',
            name='instansale_trx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_instan_trx', to='transaction.InstanSale'),
        ),
    ]
