# Generated by Django 2.1.5 on 2019-02-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20190207_1705'),
        ('billing', '0006_auto_20190207_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='ppobsale_trx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_ppob_trx', to='transaction.PpobSale'),
        ),
        migrations.AddField(
            model_name='commisionrecord',
            name='ppobsale_trx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commision_ppob_trx', to='transaction.PpobSale'),
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='ppobsale_trx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_ppob_trx', to='transaction.PpobSale'),
        ),
        migrations.AddField(
            model_name='profitrecord',
            name='ppobsale_trx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profit_ppob_trx', to='transaction.PpobSale'),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='instansale_trx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_instan_trx', to='transaction.InstanSale'),
        ),
        migrations.AlterField(
            model_name='commisionrecord',
            name='instansale_trx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commision_instan_trx', to='transaction.InstanSale'),
        ),
        migrations.AlterField(
            model_name='profitrecord',
            name='instansale_trx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profit_instan_trx', to='transaction.InstanSale'),
        ),
    ]
