# Generated by Django 2.1.5 on 2019-02-12 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('billing', '0007_auto_20190207_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_apyment', to='payment.Payment'),
        ),
    ]
