# Generated by Django 2.1.5 on 2019-02-12 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_loanpayment'),
        ('billing', '0008_billingrecord_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrecord',
            name='payment',
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='loan_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_payment', to='payment.LoanPayment'),
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='payform',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.LoanRecord'),
        ),
    ]
