# Generated by Django 2.1.5 on 2019-03-08 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20190308_1553'),
        ('billing', '0010_auto_20190212_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_transfer', to='payment.Transfer'),
        ),
    ]
