# Generated by Django 2.1.5 on 2019-03-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_billingrecord_transfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingrecord',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Billing'},
        ),
        migrations.AlterModelOptions(
            name='commisionrecord',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Komisi'},
        ),
        migrations.AlterModelOptions(
            name='loanrecord',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Pinjaman'},
        ),
        migrations.AlterModelOptions(
            name='profitrecord',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Keuntungan'},
        ),
    ]
