# Generated by Django 2.1.5 on 2019-03-31 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20190322_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrecord',
            name='bill_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_bill', to='billing.BillingRecord'),
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
