# Generated by Django 2.1.5 on 2019-02-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190207_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.CharField(choices=[('IN', 'INSTAN PRODUCT'), ('QU', 'INQUERY PRODUCT')], default='IN', max_length=2),
        ),
    ]
