# Generated by Django 2.1.5 on 2019-03-07 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_type_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['operator', 'group', 'nominal', 'product_name']},
        ),
    ]
