# Generated by Django 2.1.5 on 2019-02-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_loanpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanpayment',
            name='vitrual_cash',
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='virtual_cash',
            field=models.BooleanField(default=False),
        ),
    ]
