# Generated by Django 2.1.5 on 2019-04-09 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_bank_bankaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['bank', 'name']},
        ),
    ]
