# Generated by Django 2.1.5 on 2019-04-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankrecon', '0002_reconciliation_marker'),
        ('payment', '0007_auto_20190409_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reconsil',
            field=models.OneToOneField(blank=True, null=True, on_delete=True, to='bankrecon.Reconciliation'),
        ),
    ]
