# Generated by Django 2.1.5 on 2019-02-03 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=30, unique=True)),
                ('customer', models.CharField(max_length=30)),
                ('product_code', models.CharField(blank=True, max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closed', models.BooleanField(default=False)),
                ('create_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OP', 'OPEN'), ('IN', 'IN PROCESS'), ('CO', 'COMPLETE'), ('FL', 'FAILED')], default='OP', max_length=2)),
                ('instansale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.InstanSale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
