# Generated by Django 2.1.5 on 2019-02-07 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_type_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0002_auto_20190207_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='PpobSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('delete_on', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(editable=False, max_length=30, unique=True)),
                ('customer', models.CharField(max_length=30)),
                ('sale_type', models.CharField(choices=[('IN', 'INQUERY REQUEST'), ('PY', 'PAYMENT REQUEST')], default='IN', max_length=2)),
                ('product_code', models.CharField(blank=True, max_length=30)),
                ('nominal', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closed', models.BooleanField(default=False)),
                ('create_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ppob_create_user', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppob_product', to='product.Product')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='instansale',
            name='create_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instan_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instansale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instan_product', to='product.Product'),
        ),
        migrations.AlterField(
            model_name='status',
            name='instansale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='isntansale_status', to='transaction.InstanSale'),
        ),
        migrations.AddField(
            model_name='status',
            name='ppobsale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppobsale_status', to='transaction.PpobSale'),
        ),
    ]
