# Generated by Django 2.1.5 on 2019-02-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20190207_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='instansale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instansale_status', to='transaction.InstanSale'),
        ),
    ]
