# Generated by Django 2.1.5 on 2019-02-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20190218_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseinsale',
            name='ket',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='responseppobsale',
            name='ket',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
