# Generated by Django 2.1.5 on 2019-03-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20190317_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responseinsale',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Transaksi Topup'},
        ),
        migrations.AlterModelOptions(
            name='responseppobsale',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Transaksi Ppob'},
        ),
    ]
