# Generated by Django 2.1.5 on 2019-04-04 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20190329_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='ppob_trx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ppob_refund', to='transaction.PpobSale'),
        ),
    ]
