# Generated by Django 2.1.5 on 2019-04-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_refundrequest_ppob_trx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refundapproval',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='refundrequest',
            options={'ordering': ['-timestamp']},
        ),
    ]
