# Generated by Django 2.1.5 on 2019-03-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='application/'),
        ),
    ]
