# Generated by Django 2.1.5 on 2019-02-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20190207_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ponsel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
