# Generated by Django 2.1.5 on 2019-03-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profile_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
