# Generated by Django 2.1.5 on 2019-03-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_uploaduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='init_loan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='commision',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='limit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='loan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='saldo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
