# Generated by Django 2.1.5 on 2019-04-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankrecon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliation',
            name='marker',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
