# Generated by Django 2.1.5 on 2019-04-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankrecon', '0002_reconciliation_marker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['bank_code']},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['bank__bank_code']},
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='how_to',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
