# Generated by Django 2.2 on 2019-04-25 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('witdraw', '0001_initial'),
        ('bankrecon', '0005_auto_20190421_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliation',
            name='commision_witdraw',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='witdraw.Witdraw'),
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='resource',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Withdraw Commision'), (1, 'Transafer')], default=1),
        ),
        migrations.AlterField(
            model_name='catatan',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='bankrecon.BankAccount'),
        ),
    ]
