# Generated by Django 2.2 on 2019-05-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankrecon', '0006_auto_20190425_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliation',
            name='resource',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Withdraw Commision'), (1, 'Transfer')], default=1),
        ),
    ]
